// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIZkknaN9wG1KLbRj9Q2_5JveXdqKbGQ',
    appId: '1:263582937498:android:298337d58e8da89f4eca23',
    messagingSenderId: '263582937498',
    projectId: 'cryptowin-4d5c8',
    databaseURL: 'https://cryptowin-4d5c8-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowin-4d5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDZovcmgbGJIarwtAaq1T3YEtv7grEhg',
    appId: '1:263582937498:ios:7b796eabd13c71224eca23',
    messagingSenderId: '263582937498',
    projectId: 'cryptowin-4d5c8',
    databaseURL: 'https://cryptowin-4d5c8-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowin-4d5c8.appspot.com',
    iosClientId: '263582937498-1i7hqgdmbhmpuhk7bgphqk8b0jf6d909.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopy',
  );

}